import streamlit as st
import pandas as pd
import joblib

st.set_page_config(
    page_title="Smart House Price Prediction",
    page_icon="🏠",
    layout="centered"
)

@st.cache_resource
def load_model():
    saved_model = joblib.load("house_price_model.pkl")
    return saved_model["preprocessor"], saved_model["model"], saved_model["features"]

preprocessor, model, features = load_model()

st.title("🏠 Smart House Price Prediction")
st.markdown("**Enter the property details below and get an estimated house price instantly.**")
st.caption("Multiple Linear Regression • Machine Learning Project")
st.divider()

st.subheader("🏡 Property Details")

area = st.number_input("Area (Sqft)", min_value=500.0, max_value=11000.0, value=2500.0, step=50.0)

col1, col2 = st.columns(2)
with col1:
    bedrooms = st.number_input("Bedrooms", min_value=1, max_value=6, value=3, step=1)
with col2:
    bathrooms = st.number_input("Bathrooms", min_value=1, max_value=5, value=2, step=1)

age = st.number_input("Property Age (Years)", min_value=0.0, max_value=110.0, value=5.0, step=1.0)

location = st.selectbox("Location", ["Downtown", "Urban", "Suburban", "Rural"])
furnishing = st.selectbox("Furnishing Status", ["Furnished", "Semi-Furnished", "Unfurnished"])
property_type = st.selectbox("Property Type", ["Apartment", "Independent House", "Villa", "Studio"])

col3, col4 = st.columns(2)
with col3:
    parking = st.number_input("Parking Spaces", min_value=0, max_value=3, value=2, step=1)
with col4:
    garden = st.selectbox("Garden Available", ["Yes", "No"])

distance = st.number_input(
    "Distance to City Center (Km)",
    min_value=0.5,
    max_value=216.0,
    value=5.0,
    step=0.5
)

st.divider()

if st.button("🔮 Predict House Price", use_container_width=True):
    garden_value = 1 if garden == "Yes" else 0

    new_house = pd.DataFrame({
        "Area_Sqft": [area],
        "Bedrooms": [bedrooms],
        "Bathrooms": [bathrooms],
        "Age_Years": [age],
        "Location": [location],
        "Furnishing_Status": [furnishing],
        "Property_Type": [property_type],
        "Parking_Spaces": [parking],
        "Garden_Available": [garden_value],
        "Distance_To_City_Center_Km": [distance]
    })

    try:
        processed_input = preprocessor.transform(new_house)
        prediction = model.predict(processed_input)[0]

        st.success("Prediction generated successfully!")
        st.metric("Estimated House Price", f"₹{prediction:,.2f}")
        st.info("Estimate generated by the trained Multiple Linear Regression model.")

    except Exception as e:
        st.error("Unable to generate the prediction. Please check the model file and input configuration.")
        st.exception(e)

st.divider()

with st.expander("ℹ️ About this project"):
    st.write(
        "This application predicts house prices from property characteristics "
        "using a Multiple Linear Regression model."
    )
    st.write("**Built by:** Priyadharshini")
    st.write("**Project:** Smart House Price Prediction")
